// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.RegularExpressions;

namespace Repo.Ef.Models
{
    public partial class Commento
    {

        public Commento()
        {
         
            File = new HashSet<FileStorage>();
        }

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int CommentId { get; set; }
        public string Content { get; set; }
        public DateTime? Timestamp { get; set; }
        public string UserId { get; set; }    
        public int? PostId { get; set; }

        public virtual Post Post { get; set; }
        public virtual ICollection<FileStorage> File { get; set; }
        public virtual ApplicationUser User { get; set; }
    }
}