// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Repo.Ef.Models
{
    public partial class Evento
    {
        public Evento()
        {
            Group = new HashSet<Gruppo>();
            User = new HashSet<ApplicationUser>();
        }

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int EventId { get; set; }
        public string EventName { get; set; }
        public string Description { get; set; }
        public DateTime? Date { get; set; }
        public string Location { get; set; }
        public string CreatorId { get; set; }       
        public virtual ICollection<Gruppo> Group { get; set; }
        public virtual ICollection<ApplicationUser> User { get; set; }
        public string UserId { get; set; }


    }
}