// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Repo.Ef.Models
{
    public partial class Gruppo
    {
        public Gruppo()
        {
            Post = new HashSet<Post>();
            Event = new HashSet<Evento>();
            User = new HashSet<ApplicationUser>();
        }
        [Key]
        public int GroupId { get; set; }
        public string GroupName { get; set; }
        public string Description { get; set; }
        public DateTime? CreationDate { get; set; }

        public virtual ICollection<Post> Post { get; set; }
        public string UserId { get; set; }

        public virtual ICollection<Evento> Event { get; set; }
        public virtual ICollection<ApplicationUser> User { get; set; }
    }
}