// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Repo.Ef.Models
{
    public partial class Post
    {
        public Post()
        {
            UserNavigation = new HashSet<ApplicationUser>();
            Commento = new HashSet<Commento>();
        }

        [Key]
        public int PostId { get; set; }
        public string Content { get; set; }
        public DateTime? Timestamp { get; set; }
        public string UserId { get; set; }
        public int? FileId { get; set; }
        public int? GroupId { get; set; }

        public virtual FileStorage File { get; set; }
        public virtual Gruppo Group { get; set; }
        public virtual ApplicationUser User { get; set; }

        public virtual ICollection<ApplicationUser> UserNavigation { get; set; }
        public virtual ICollection<Commento> Commento { get; set; }

    }
}