// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Repo.Ef
{
    public partial class Boss
    {
        [Key]
        [Column("BossID")]
        public int BossId { get; set; }
        public int Pvd { get; set; }
        public int Pa { get; set; }
        public int Pd { get; set; }
        public int Ctk { get; set; }
        public int PvPost { get; set; }
        public int PaPost { get; set; }
        public int PdPost { get; set; }
        public int CtkPost { get; set; }
    }
}