// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Repo.Ef
{
    public partial class DropUser
    {
        [Key]
        [Column("DropUsersID")]
        public int DropUsersId { get; set; }
        [Column("PgID")]
        public int PgId { get; set; }
        public int ItemtId { get; set; }
        [Column("level")]
        public int Level { get; set; }

        [ForeignKey(nameof(ItemtId))]
        [InverseProperty(nameof(Item.DropUsers))]
        public virtual Item Itemt { get; set; }
        [ForeignKey(nameof(PgId))]
        [InverseProperty("DropUsers")]
        public virtual Pg Pg { get; set; }
    }
}