// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Repo.Ef
{
    public partial class Item
    {
        public Item()
        {
            DropUsers = new HashSet<DropUser>();
        }

        [Key]
        [Column("ItemsID")]
        public Guid ItemsId { get; set; }
        [Required]
        [StringLength(250)]
        public string Name { get; set; }
        [Required]
        [Column(TypeName = "text")]
        public string Description { get; set; }

        [InverseProperty(nameof(DropUser.Itemt))]
        public virtual ICollection<DropUser> DropUsers { get; set; }
    }
}