// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Repo.Ef
{
    public partial class Move
    {
        [Key]
        [Column("MovesID")]
        public Guid MovesId { get; set; }
        [Required]
        [StringLength(250)]
        public string Description { get; set; }


        public string Name { get; set; }
        [Column(TypeName = "text")]
        public string Image { get; set; }
        [Column("TypologyID")]
        public int TypologyId { get; set; }
        [Column("PgID")]
        public Guid PgId { get; set; }

        [ForeignKey(nameof(PgId))]
        [InverseProperty("Moves")]
        public virtual Pg Pg { get; set; }
        [ForeignKey(nameof(TypologyId))]
        [InverseProperty("Moves")]
        public virtual Typology Typology { get; set; }
    }
}