// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Repo.Ef
{
    public partial class StatisticBase
    {
        [Key]
        [Column("StatisticsID")]
        public Guid StatisticBaseId { get; set; }

        public int Pvd { get; set; }
        public int Pa { get; set; }
        public int Pd { get; set; }
        public int Ctk { get; set; }
        [Required]
        [StringLength(100)]
        public string Typology { get; set; }

    }
}