// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Repo.Ef
{
    [Table("Typology")]
    public partial class Typology
    {
        public Typology()
        {
            Moves = new HashSet<Move>();
        }

        [Key]
        [Column("TypologyID")]
        public int TypologyId { get; set; }
        [Required]
        [StringLength(250)]
        public string Name { get; set; }
        [Required]
        [Column(TypeName = "text")]
        public string Value { get; set; }

        [InverseProperty(nameof(Move.Typology))]
        public virtual ICollection<Move> Moves { get; set; }
    }
}