// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Models
{
    public partial class FileStorageRequest
    {      
        public string FileName { get; set; }
        public string FilePath { get; set; }
        public string FileType { get; set; }       
    }
}