// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Models
{
    public partial class GruppoRequest
    {
    
        public string GroupName { get; set; }
        public string Description { get; set; }
        public string IdUser { get; set; }
        public int GroupId { get; set; }

        public DateTime? CreationDate { get; set; }     
    }
}