// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UniConnect.Repo.EF.Models
{
    public partial class AspNetUsers
    {
        public AspNetUsers()
        {
            AspNetUserClaims = new HashSet<AspNetUserClaims>();
            AspNetUserLogins = new HashSet<AspNetUserLogins>();
            AspNetUserTokens = new HashSet<AspNetUserTokens>();
            Commento = new HashSet<Commento>();
            Pg = new HashSet<Pg>();
            Post = new HashSet<Post>();
            Event = new HashSet<Evento>();
            File = new HashSet<FileStorage>();
            Group = new HashSet<Gruppo>();
            PostNavigation = new HashSet<Post>();
            Role = new HashSet<AspNetRoles>();
        }

        public string Id { get; set; }
        public string UserName { get; set; }
        public string NormalizedUserName { get; set; }
        public string Email { get; set; }
        public string NormalizedEmail { get; set; }
        public bool EmailConfirmed { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string ConcurrencyStamp { get; set; }
        public string PhoneNumber { get; set; }
        public bool PhoneNumberConfirmed { get; set; }
        public bool TwoFactorEnabled { get; set; }
        public DateTimeOffset? LockoutEnd { get; set; }
        public bool LockoutEnabled { get; set; }
        public int AccessFailedCount { get; set; }
        public string Avatar { get; set; }

        public virtual ICollection<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual ICollection<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual ICollection<AspNetUserTokens> AspNetUserTokens { get; set; }
        public virtual ICollection<Commento> Commento { get; set; }
        public virtual ICollection<Pg> Pg { get; set; }
        public virtual ICollection<Post> Post { get; set; }

        public virtual ICollection<Evento> Event { get; set; }
        public virtual ICollection<FileStorage> File { get; set; }
        public virtual ICollection<Gruppo> Group { get; set; }
        public virtual ICollection<Post> PostNavigation { get; set; }
        public virtual ICollection<AspNetRoles> Role { get; set; }
    }
}