// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UniConnect.Repo.EF.Models
{
    public partial class Commento
    {
        public int CommentId { get; set; }
        public string Content { get; set; }
        public DateTime? Timestamp { get; set; }
        public string UserId { get; set; }
        public int? FileId { get; set; }

        public virtual FileStorage File { get; set; }
        public virtual AspNetUsers User { get; set; }
    }
}