// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UniConnect.Repo.EF.Models
{
    public partial class FileStorage
    {
        public FileStorage()
        {
            Commento = new HashSet<Commento>();
            Post = new HashSet<Post>();
            User = new HashSet<AspNetUsers>();
        }

        public int FileId { get; set; }
        public string FileName { get; set; }
        public string FilePath { get; set; }
        public string FileType { get; set; }

        public virtual ICollection<Commento> Commento { get; set; }
        public virtual ICollection<Post> Post { get; set; }

        public virtual ICollection<AspNetUsers> User { get; set; }
    }
}